name: CD Pipeline

# Voer de workflow uit op elke push naar de main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the project (if necessary)
      - name: Build project
        run: npm run build # Pas dit aan als je een build-stap hebt

      # Deploy to server
      - name: Deploy to server
        run: |
          # Dit is een voorbeeld van een SSH-commando om je applicatie te deployen
          ssh user@your-server "cd /path/to/your/app && git pull origin main && npm install && pm2 restart all"